# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  - group: secret
  - name: imageName
    value: pipelines-go
  - name: dockerHub
    value: 'dockerhub'

steps:
- script: |
    docker build -f Dockerfile -t $(imageName):$(build.buildId) -t $(imageName):latest .
    docker login -u $(DOCKER_HUB_USER) -p $(DOCKER_HUB_PWD)
    echo $(DOCKER_HUB_USER)/$(imageName):$(build.buildId)
    docker push $(DOCKER_HUB_USER)/$(imageName):$(build.buildId)
  displayName: Docker build
  
