# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'pipelines-go:$(build.buildId)'
  dockerHub: 'dockerhub'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: Build image
- script: docker push $(imageName):latest
  displayName: Push image
  
